server:
  port: 80

spring:
  datasource:
    druid:
      mysql:
        url: jdbc:mysql://localhost/company_score?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: pzy123456.
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          maximum-pool-size: 50
          minimum-idle: 10
          idle-timeout: 30000 # 30 seconds
          connection-timeout: 30000 # 30 seconds
          max-lifetime: 1800000 # 30 minutes
mybatis:
  mapper-locations: classpath:com/system/assessment/mapper/*.xml
  type-aliases-package: com.system.assessment.pojo
  type-handlers-package: "com.system.assessment.constants.handler"
  configuration:
    map-underscore-to-camel-case: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB




logging:
  config: classpath:log4j2.xml

swagger:
  enabled: true
  title: 成长评估系统项目Api接口文档
  description: 成长评估系统
  version: "1.0"
  apply-default-response-messages: false
  global-response-message:
    get:
      - code: 200
        message: OK
      - code: 400
        message: Bad Request
      - code: 500
        message: Internal Server Error
      - code: 999
        message: Unknown Error
    post:
      - code: 200
        message: OK
      - code: 400
        message: Bad Request
      - code: 500
        message: Internal Server Error
      - code: 999
        message: Unknown Error
    put:
      - code: 200
        message: OK
      - code: 400
        message: Bad Request
      - code: 500
        message: Internal Server Error
      - code: 999
        message: Unknown Error
    delete:
      - code: 200
        message: OK
      - code: 400
        message: Bad Request
      - code: 500
        message: Internal Server Error
      - code: 999
        message: Unknown Error